workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Clean
        script: |
          flutter clean
          rm -rf android/app/src/main/java/io/flutter/plugins/
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - jeganmanogaran1995@gmail.com
        notify:
          success: true
          failure: true
